[build]
builder = "nixpacks"

[deploy]
startCommand = "ENVIRONMENT=production bash scripts/start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
