/**
 * Development-only People fixture data.
 *
 * Examples:
 *   bun run seed:people -- --viewer <email|username|id> --confirm-dev
 *   bun run seed:people:dry-run -- --viewer <email|username|id>
 */
import type { PrismaClient } from "@prisma/client";
import {
  PEOPLE_DEV_ACCEPTED,
  PEOPLE_DEV_ACCEPTED_CONNECTIONS,
  PEOPLE_DEV_ACTIVE_IDS,
  PEOPLE_DEV_CONVERSATIONS,
  PEOPLE_DEV_HOME_ACTIVITIES,
  PEOPLE_DEV_MUTUAL_BRIDGES,
  PEOPLE_DEV_ORGANIZATION_ID,
  PEOPLE_DEV_ORGANIZATION_PERSON_IDS,
  PEOPLE_DEV_ORGANIZATION_SLUG,
  PEOPLE_DEV_PEOPLE,
  PEOPLE_DEV_PENDING_CONNECTIONS,
  PEOPLE_DEV_SEED_PREFIX,
  PEOPLE_DEV_SUGGESTIONS,
  PEOPLE_DEV_WORKSPACES,
  assertSafePeopleDevEnvironment,
  buildPeopleDevCleanupSelectors,
  buildPeopleDevConnectionPairKey,
  describePeopleDevDatabase,
  getPeopleDevFixtureSummary,
  parsePeopleDevArgs,
  type PeopleDevCliOptions,
} from "../src/lib/people-dev-seed";
import { buildDmPairKey } from "../src/lib/dm-pair-key";

const DAY_MS = 24 * 60 * 60 * 1000;
const HOUR_MS = 60 * 60 * 1000;

type Viewer = {
  id: string;
  name: string;
  email: string;
  username: string | null;
};

async function main(): Promise<void> {
  const options = parsePeopleDevArgs(process.argv.slice(2));
  assertSafePeopleDevEnvironment(options, process.env);

  if (options.mode === "dry-run") {
    printDryRun(options);
    return;
  }

  const database = describePeopleDevDatabase(process.env.DATABASE_URL!);
  console.log(`People seed target: host=${database.host} database=${database.database}`);

  const { PrismaClient } = await import("@prisma/client");
  const prisma = new PrismaClient();
  try {
    const viewer = await resolveViewer(prisma, options.viewer);
    if (viewer.id.startsWith(PEOPLE_DEV_SEED_PREFIX)) {
      throw new Error("A seeded fixture user cannot be used as the viewer");
    }
    console.log(`People seed viewer: ${viewer.name} (${viewer.username ?? viewer.email})`);

    if (options.mode === "seed") {
      const summary = await seedPeopleDevelopment(prisma, viewer);
      printSummary("Seed complete", viewer, summary);
    } else if (options.mode === "presence") {
      const summary = await refreshPresence(prisma);
      printSummary("Presence refresh complete", viewer, summary);
    } else {
      const summary = await cleanupPeopleDevelopment(prisma, viewer.id);
      printSummary("Cleanup complete", viewer, summary);
    }
  } finally {
    await prisma.$disconnect();
  }
}

async function resolveViewer(prisma: PrismaClient, viewerInput: string): Promise<Viewer> {
  const usernameInput = viewerInput.replace(/^@/, "");
  const viewer = await prisma.user.findFirst({
    where: {
      OR: [
        { id: viewerInput },
        { email: { equals: viewerInput, mode: "insensitive" } },
        { username: { equals: usernameInput, mode: "insensitive" } },
      ],
    },
    select: { id: true, name: true, email: true, username: true },
  });
  if (!viewer) {
    throw new Error(`Viewer not found for the supplied email, username, or id`);
  }
  return viewer;
}

async function seedPeopleDevelopment(prisma: PrismaClient, viewer: Viewer) {
  const now = new Date();
  const inactiveById = new Map<string, Date>([
    [PEOPLE_DEV_ACCEPTED[2]!.id, new Date(now.getTime() - 8 * HOUR_MS)],
    [PEOPLE_DEV_ACCEPTED[3]!.id, new Date(now.getTime() - 4 * DAY_MS)],
  ]);

  return prisma.$transaction(async (tx) => {
    for (const person of PEOPLE_DEV_PEOPLE) {
      const lastActiveAt = person.active
        ? new Date(
            now.getTime() -
              (PEOPLE_DEV_ACTIVE_IDS.indexOf(
                person.id as (typeof PEOPLE_DEV_ACTIVE_IDS)[number],
              ) +
                1) *
                45_000,
          )
        : inactiveById.get(person.id) ?? new Date(now.getTime() - 14 * DAY_MS);
      const data = {
        name: person.name,
        email: person.email,
        username: person.username,
        usernameAutoGenerated: false,
        messagePrivacy: "connections_and_shared",
        discoverableByEmail: true,
        lastActiveAt,
        showActiveStatus: true,
        emailVerified: true,
        image: person.image,
        profileTitle: person.profileTitle,
        profileOrganization: person.profileOrganization,
        profileLocation: person.profileLocation,
        profileBio: `People development demo profile for ${person.name}.`,
      };
      await tx.user.upsert({
        where: { id: person.id },
        create: { id: person.id, ...data },
        update: data,
      });
    }

    for (const connection of PEOPLE_DEV_ACCEPTED_CONNECTIONS) {
      const acceptedAt = new Date(now.getTime() - connection.acceptedDaysAgo * DAY_MS);
      const data = {
        requesterId: viewer.id,
        recipientId: connection.personId,
        status: "accepted",
        pairKey: buildPeopleDevConnectionPairKey(viewer.id, connection.personId),
        createdAt: new Date(acceptedAt.getTime() - 2 * DAY_MS),
        updatedAt: acceptedAt,
      };
      await tx.connection.upsert({
        where: { pairKey: data.pairKey },
        create: data,
        update: data,
      });
    }

    for (const connection of PEOPLE_DEV_MUTUAL_BRIDGES) {
      const data = {
        requesterId: connection.acceptedPersonId,
        recipientId: connection.suggestionPersonId,
        status: "accepted",
        pairKey: buildPeopleDevConnectionPairKey(
          connection.acceptedPersonId,
          connection.suggestionPersonId,
        ),
        createdAt: new Date(now.getTime() - 60 * DAY_MS),
        updatedAt: new Date(now.getTime() - 30 * DAY_MS),
      };
      await tx.connection.upsert({
        where: { pairKey: data.pairKey },
        create: data,
        update: data,
      });
    }

    // Suggestions must remain eligible: remove only viewer-to-fixture suggestion rows.
    await tx.connection.deleteMany({
      where: {
        pairKey: {
          in: PEOPLE_DEV_SUGGESTIONS.map((person) =>
            buildPeopleDevConnectionPairKey(viewer.id, person.id),
          ),
        },
      },
    });

    for (const connection of PEOPLE_DEV_PENDING_CONNECTIONS) {
      const incoming = connection.direction === "incoming";
      const requestedAt = new Date(now.getTime() - connection.hoursAgo * HOUR_MS);
      const data = {
        requesterId: incoming ? connection.personId : viewer.id,
        recipientId: incoming ? viewer.id : connection.personId,
        status: "pending",
        pairKey: buildPeopleDevConnectionPairKey(viewer.id, connection.personId),
        createdAt: requestedAt,
        updatedAt: requestedAt,
      };
      await tx.connection.upsert({
        where: { pairKey: data.pairKey },
        create: data,
        update: data,
      });
    }

    for (const [index, fixture] of PEOPLE_DEV_CONVERSATIONS.entries()) {
      const dmPairKey = buildDmPairKey(viewer.id, fixture.personId);
      await tx.conversation.upsert({
        where: { id: fixture.id },
        create: {
          id: fixture.id,
          isGroup: false,
          dmPairKey,
          createdAt: new Date(now.getTime() - 70 * DAY_MS),
        },
        update: { name: null, image: null, isGroup: false, teamId: null, dmPairKey },
      });
      await tx.conversationParticipant.deleteMany({
        where: {
          conversationId: fixture.id,
          userId: { notIn: [viewer.id, fixture.personId] },
        },
      });
      for (const [participantIndex, userId] of [viewer.id, fixture.personId].entries()) {
        const participantId = `${PEOPLE_DEV_SEED_PREFIX}participant-${index + 1}-${participantIndex + 1}`;
        await tx.conversationParticipant.upsert({
          where: { id: participantId },
          create: {
            id: participantId,
            conversationId: fixture.id,
            userId,
            role: "member",
          },
          update: { conversationId: fixture.id, userId, role: "member" },
        });
      }
      for (const message of fixture.messages) {
        const senderId = message.sender === "viewer" ? viewer.id : fixture.personId;
        const data = {
          content: message.content,
          mediaUrl: null,
          mediaType: null,
          conversationId: fixture.id,
          senderId,
          replyToId: null,
          mentionedUserIds: "[]",
          createdAt: new Date(now.getTime() - message.daysAgo * DAY_MS),
        };
        await tx.directMessage.upsert({
          where: { id: message.id },
          create: { id: message.id, ...data },
          update: data,
        });
      }
    }

    await tx.organization.upsert({
      where: { id: PEOPLE_DEV_ORGANIZATION_ID },
      create: {
        id: PEOPLE_DEV_ORGANIZATION_ID,
        name: "People Development Collective",
        slug: PEOPLE_DEV_ORGANIZATION_SLUG,
        status: "active",
        accountType: "enterprise",
        workspaceLimit: PEOPLE_DEV_WORKSPACES.length,
        ssoRequired: false,
      },
      update: {
        name: "People Development Collective",
        slug: PEOPLE_DEV_ORGANIZATION_SLUG,
        status: "active",
        accountType: "enterprise",
        workspaceLimit: PEOPLE_DEV_WORKSPACES.length,
        ssoRequired: false,
      },
    });
    const organizationUserIds = [viewer.id, ...PEOPLE_DEV_ORGANIZATION_PERSON_IDS];
    await tx.organizationMembership.deleteMany({
      where: {
        organizationId: PEOPLE_DEV_ORGANIZATION_ID,
        userId: { notIn: organizationUserIds },
      },
    });
    for (const [index, userId] of organizationUserIds.entries()) {
      const membershipId = `${PEOPLE_DEV_SEED_PREFIX}organization-membership-${index + 1}`;
      await tx.organizationMembership.upsert({
        where: { id: membershipId },
        create: {
          id: membershipId,
          organizationId: PEOPLE_DEV_ORGANIZATION_ID,
          userId,
          role: "org_member",
          joinedAt: new Date(now.getTime() - 20 * DAY_MS),
        },
        update: {
          organizationId: PEOPLE_DEV_ORGANIZATION_ID,
          userId,
          role: "org_member",
          joinedAt: new Date(now.getTime() - 20 * DAY_MS),
        },
      });
    }

    const personById = new Map(PEOPLE_DEV_PEOPLE.map((person) => [person.id, person]));
    for (const workspace of PEOPLE_DEV_WORKSPACES) {
      await tx.team.upsert({
        where: { id: workspace.id },
        create: {
          id: workspace.id,
          name: workspace.name,
          location: workspace.location,
          image: null,
          inviteCode: workspace.inviteCode,
          organizationId: workspace.organizationId,
        },
        update: {
          name: workspace.name,
          location: workspace.location,
          image: null,
          inviteCode: workspace.inviteCode,
          organizationId: workspace.organizationId,
        },
      });
      const memberUserIds = [viewer.id, ...workspace.memberPersonIds];
      await tx.teamMember.deleteMany({
        where: { teamId: workspace.id, userId: { notIn: memberUserIds } },
      });
      for (const userId of memberUserIds) {
        await tx.teamMember.upsert({
          where: { userId_teamId: { userId, teamId: workspace.id } },
          create: {
            userId,
            teamId: workspace.id,
            role: userId === viewer.id ? "owner" : "member",
          },
          update: { role: userId === viewer.id ? "owner" : "member" },
        });
      }
    }

    for (const activity of PEOPLE_DEV_HOME_ACTIVITIES) {
      const actor = personById.get(activity.actorPersonId);
      if (!actor) throw new Error(`Missing Home fixture actor ${activity.actorPersonId}`);
      const targetUserId =
        activity.target === "viewer"
          ? viewer.id
          : activity.target === "actor"
            ? actor.id
            : null;
      const targetName =
        activity.target === "viewer"
          ? viewer.name
          : activity.target === "actor"
            ? actor.name
            : null;
      const metadata = JSON.stringify({
        ...activity.metadata,
        ...(targetUserId ? { targetUserId, targetName } : {}),
      });
      const data = {
        teamId: activity.workspaceId,
        userId: actor.id,
        type: activity.type,
        metadata,
        createdAt: new Date(now.getTime() - activity.minutesAgo * 60_000),
      };
      await tx.teamActivity.upsert({
        where: { id: activity.id },
        create: { id: activity.id, ...data },
        update: data,
      });
    }

    return getPeopleDevFixtureSummary();
  },
  // The fixture is upsert-heavy and outgrew Prisma's 5s interactive default.
  { maxWait: 20_000, timeout: 120_000 });
}

async function refreshPresence(prisma: PrismaClient) {
  const result = await prisma.user.updateMany({
    where: { id: { in: [...PEOPLE_DEV_ACTIVE_IDS] } },
    data: { lastActiveAt: new Date(), showActiveStatus: true },
  });
  return { activeUsersRefreshed: result.count, expected: PEOPLE_DEV_ACTIVE_IDS.length };
}

async function cleanupPeopleDevelopment(prisma: PrismaClient, viewerId: string) {
  const selectors = buildPeopleDevCleanupSelectors(viewerId);
  return prisma.$transaction(async (tx) => {
    const activities = await tx.teamActivity.deleteMany({
      where: { id: { in: selectors.activityIds } },
    });
    const teams = await tx.team.deleteMany({
      where: { id: { in: selectors.teamIds } },
    });
    const conversations = await tx.conversation.deleteMany({
      where: {
        OR: [
          { id: { in: selectors.conversationIds } },
          { dmPairKey: { in: selectors.dmPairKeys } },
        ],
      },
    });
    const connections = await tx.connection.deleteMany({
      where: {
        OR: [
          { id: { in: selectors.connectionIds } },
          { pairKey: { in: selectors.connectionPairKeys } },
        ],
      },
    });
    const organizations = await tx.organization.deleteMany({
      where: { id: { in: selectors.organizationIds } },
    });
    const users = await tx.user.deleteMany({
      where: {
        id: { in: selectors.userIds, startsWith: PEOPLE_DEV_SEED_PREFIX },
      },
    });
    return {
      conversationsDeleted: conversations.count,
      connectionsDeleted: connections.count,
      activitiesDeleted: activities.count,
      teamsDeleted: teams.count,
      organizationsDeleted: organizations.count,
      usersDeleted: users.count,
    };
  });
}

function printDryRun(options: PeopleDevCliOptions): void {
  const databaseUrl = process.env.DATABASE_URL?.trim();
  const target = databaseUrl
    ? (() => {
        try {
          const database = describePeopleDevDatabase(databaseUrl);
          return `host=${database.host} database=${database.database}`;
        } catch {
          return "unconfigured or non-PostgreSQL (allowed for dry-run only)";
        }
      })()
    : "unconfigured (allowed for dry-run only)";
  console.log("People seed dry-run: no database client was created");
  console.log(`Mode: ${options.mode}`);
  console.log(`Viewer selector supplied: yes`);
  console.log(`Configured target: ${target}`);
  console.log(JSON.stringify(getPeopleDevFixtureSummary(), null, 2));
  printCommands();
}

function printSummary(
  title: string,
  viewer: Viewer,
  summary: Record<string, unknown>,
): void {
  console.log(title);
  console.log(`Viewer: ${viewer.name} (${viewer.username ?? viewer.email})`);
  console.log(JSON.stringify(summary, null, 2));
  printCommands();
}

function printCommands(): void {
  console.log("Commands:");
  console.log("  bun run seed:people:dry-run -- --viewer <email|username|id>");
  console.log("  bun run seed:people -- --viewer <email|username|id> --confirm-dev");
  console.log("  bun run seed:people:active -- --viewer <email|username|id> --confirm-dev");
  console.log("  bun run seed:people:cleanup -- --viewer <email|username|id> --confirm-dev");
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : "Unknown People seed failure";
  console.error(`People seed failed: ${redactDatabaseUrls(message)}`);
  process.exitCode = 1;
});

function redactDatabaseUrls(message: string): string {
  return message.replace(/postgres(?:ql)?:\/\/[^\s'"]+/gi, "[redacted database URL]");
}
